EXTRA_TOKENS = [
    "<L>",
    "<R>",
    "<R0>",
    "<R1>",
    "<R2>",
    "<R3>",
    "<R4>",
    "<R5>",
    "<R6>",
    "<R7>",
    "<R8>",
    "<R9>",
    "<R10>",
    "<R11>",
    "<R12>",
    "<R13>",
    "<R14>",
    "<R15>",
    "<R16>",
    "<R17>",
    "<R18>",
    "<R19>",
    "<R20>",
    "<R21>",
    "<R22>",
    "<R23>",
    "<R24>",
    "<R25>",
    "<R26>",
    "<R27>",
    "<R28>",
    "<R29>",
    "<R30>",
]

UPOS = {
    "ADJ": "adjective",
    "ADP": "adposition",
    "ADV": "adverb",
    "AUX": "auxiliary",
    "CONJ": "conjunction",
    "CCONJ": "coordinating conjunction",
    "DET": "determiner",
    "INTJ": "interjection",
    "NOUN": "noun",
    "NUM": "numeral",
    "PART": "particle",
    "PRON": "pronoun",
    "PROPN": "proper noun",
    "PUNCT": "punctuation",
    "SCONJ": "subordinating conjunction",
    "SYM": "symbol",
    "VERB": "verb",
    "X": "other",
    "EOL": "end of line",
    "SPACE": "space",
}

SEM_DEPS = [
    ":'re",
    ":15",
    ":16",
    ":2",
    ":20",
    ":24",
    ":26",
    ":3",
    ":39",
    ":4",
    ":5",
    ":5days",
    ":7",
    ":@",
    ":ARG0",
    ":ARG1",
    ":ARG2",
    ":SIMILAR",
    ":a",
    ":aboard",
    ":about",
    ":above",
    ":abt",
    ":acl",
    ":across",
    ":advcl",
    ":advmod",
    ":af",
    ":after",
    ":after1a.m",
    ":against",
    ":agianst",
    ":all",
    ":along",
    ":alongside",
    ":amid",
    ":amod",
    ":among",
    ":amongst",
    ":any",
    ":appos",
    ":around",
    ":as",
    ":at",
    ":attr",
    ":aux",
    ":auxpass",
    ":back",
    ":because",
    ":been",
    ":before",
    ":behind",
    ":below",
    ":beneath",
    ":beside",
    ":besides",
    ":beteween",
    ":between",
    ":betwwn",
    ":beyond",
    ":btw",
    ":but",
    ":by",
    ":case",
    ":cc",
    ":ccomp",
    ":compound",
    ":conj",
    ":date",
    ":deep",
    ":deeply",
    ":dep",
    ":despite",
    ":det",
    ":directly",
    ":do",
    ":down",
    ":due",
    ":during",
    ":early",
    ":elsewhere",
    ":especially",
    ":even",
    ":exactly",
    ":except",
    ":exclusively",
    ":expl",
    ":far",
    ":fir",
    ":for",
    ":form",
    ":fr",
    ":from",
    ":ft",
    ":hard",
    ":have",
    ":how",
    ":i.e",
    ":i.e.",
    ":if",
    ":immediately",
    ":in",
    ":infront",
    ":inside",
    ":inspite",
    ":instead",
    ":intj",
    ":into",
    ":is",
    ":just",
    ":kn",
    ":like",
    ":likes",
    ":literally",
    ":madly",
    ":mark",
    ":maybe",
    ":meta",
    ":more",
    ":mostly",
    ":much",
    ":near",
    ":nearby",
    ":nmod",
    ":not",
    ":now",
    ":npadvmod",
    ":nummod",
    ":obviously",
    ":of",
    ":off",
    ":og",
    ":on",
    ":one",
    ":online",
    ":only",
    ":onto",
    ":opposite",
    ":oprd",
    ":out",
    ":outside",
    ":outta",
    ":over",
    ":overnight",
    ":parataxis",
    ":particularly",
    ":past",
    ":pcomp",
    ":per",
    ":poss",
    ":post",
    ":preferably",
    ":prep",
    ":probably",
    ":professionally",
    ":prt",
    ":punct",
    ":rather",
    ":really",
    ":relcl",
    ":right",
    ":sendig",
    ":significantly",
    ":simply",
    ":since",
    ":so",
    ":someone",
    ":soon",
    ":specially",
    ":specifically",
    ":straight",
    ":strictly",
    ":such",
    ":symmetrical",
    ":than",
    ":then",
    ":though",
    ":throug",
    ":through",
    ":throughout",
    ":till",
    ":to",
    ":toour",
    ":toward",
    ":towards",
    ":under",
    ":unlike",
    ":until",
    ":up",
    ":upon",
    ":v",
    ":v.",
    ":versus",
    ":very",
    ":via",
    ":vis",
    ":vs",
    ":vs.",
    ":w",
    ":what",
    ":when",
    ":while",
    ":whilst",
    ":wit",
    ":with",
    ":within",
    ":without",
    ":xcomp",
]

SYN_DEPS = {
    "ACL": "Clausal modifier of noun",
    "ACOMP": "Adjectival complement",
    "ADVCL": "Adverbial clause modifier",
    "ADVMOD": "Adverbial modifier",
    "AGENT": "Agent",
    "AMOD": "Adjectival modifier",
    "APPOS": "Appositional modifier",
    "ATTR": "Attribute",
    "AUX": "Auxiliary",
    "AUXPASS": "Auxiliary (passive)",
    "CASE": "Case marker",
    "CC": "Coordinating conjunction",
    "CCOMP": "Clausal complement",
    "COMPOUND": "Compound modifier",
    "CONJ": "Conjunct",
    "CSUBJ": "Clausal subject",
    "CSUBJPASS": "Clausal subject (passive)",
    "DATIVE": "Dative",
    "DEP": "Unclassified dependent",
    "DET": "Determiner",
    "DOBJ": "Direct Object",
    "EXPL": "Expletive",
    "INTJ": "Interjection",
    "MARK": "Marker",
    "META": "Meta modifier",
    "NEG": "Negation modifier",
    "NMOD": "Modifier of nominal",
    "NPADVMOD": "Noun phrase as adverbial modifier",
    "NSUBJ": "Nominal subject",
    "NSUBJPASS": "Nominal subject (passive)",
    "NUMMOD": "Number modifier",
    "OPRD": "Object predicate",
    "PARATAXIS": "Parataxis",
    "PCOMP": "Complement of preposition",
    "POBJ": "Object of preposition",
    "POSS": "Possession modifier",
    "PRECONJ": "Pre-correlative conjunction",
    "PREDET": "Pre-determiner",
    "PREP": "Prepositional modifier",
    "PRT": "Particle",
    "PUNCT": "Punctuation",
    "QUANTMOD": "Modifier of quantifier",
    "RELCL": "Relative clause modifier",
    "ROOT": "Root",
    "XCOMP": "Open clausal complement",
}
